### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjava#16]
In order to launch we should have:

- [x] java as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] at least 10 problems
- [x] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-java.md`)
- [x] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [ ] toggle `"active"` to `true` in `config.json`

**Comment by kytrinyx** [comment]
As a starting point, I have added incomplete (and wrong) documentation for how to get started: http://help.exercism.io/getting-started-with-java.html

I can't figure out what the steps are to run the tests locally.

Given that I have the exercism CLI installed (https://github.com/exercism/cli/releases/latest), and that it is configured, I want to be able to say:

```
exercism fetch java bob
```

And then follow some sort of instructions to be able to run the tests.

What files would I need to download from this repository (or elsewhere) in order to do that?

/cc @MoreNaruto @brmenchl @edrobal @chelseakomlo @charltonaustin @gitjulia @Contraption

**Comment by Contraption** [comment]
I was able to follow the instructions and run the test with "gradle test"

What I did was:
- Install exercism via homebrew
- Go to exercism/java/bob
- Run "gradle test", I had 18 failed tests
- Wrote some simple implementation, ran "gradle test" again and had 13 failed tests

**Comment by kytrinyx** [comment]
@Contraption I'm assuming that you have gradle in your classpath. What happens if you don't have gradle installed on your machine?

**Comment by Contraption** [comment]
@kytrinyx Hmm, is it reasonable to include the gradle wrapper in the repo, so people can just use ./gradlew?

**Comment by pietvandongen** [comment]
I didn't have gradle installed, so when I went to `~/exercism/java/bob` and ran `gradle test` I got:

```bash
Piets-MBP:bob pietvandongen$ gradle test
-bash: gradle: command not found
```

**Comment by kytrinyx** [comment]
@Contraption it is, but I'll need to write some code in order to be able to serve it up using the exercism CLI. It's not very hard, but I have a lot on my plate at the moment.

@pietvandongen That's great! We'll also need to know how to install gradle on windows (and perhaps linux, though linux peeps tend to know how to figure that out for themselves).

**Comment by pietvandongen** [comment]
@kytrinyx Okey, here's what I did on Windows (7, 64 bit).

I first installed the exercism-cli per the website's instructions, which went smoothly. Then I did an ``exercism fetch java bob``, which put everything in my home directory, under ``exercism\java\bob``.

Then I went into the directory (with cmd) and typed ``gradle test``. I got the familiar error:

```
'gradle' is not recognized as an internal or external command,
operable or batch file.
```

So I installed gradle, like so:

- I went to http://gradle.org/installation
- I downloaded gradle 2.2.1 (I got a big green button in the right column of the page)
- I unpacked the ZIP file, which contained a folder (``gradle-2.2.1``) and copied it to a convenient location.
- I added that location + ``\bin`` to my PATH, so I can now run ``gradle``.

After this, I went back to my ``exercism\java\bob`` folder (still with CMD / terminal) and ran:

``gradle test``

This worked, I got a long trace of tests that failed and a failed build.

**Comment by kytrinyx** [comment]
@pietvandongen Thank you! I think this is enough to get the documentation fixed, and launch the track.

**Comment by kytrinyx** [comment]
OK, everyone! I'v updated the documentation and activated the Java track (deploying now).

I'd appreciate it if people check in regularly to help provide some feedback on people's solutions.

Since launching exercism, Haskell has been by far the most successful track. I believe that one reason for this is that there is at least one person there who makes sure that every submission receives feedback within 24 hours.

I believe a second factor of the track's success is that the feedback that is provided doesn't directly tell people what to do, but respectfully asks questions, challenging people to think about different aspects of their solution.

Thanks so much for helping get this kicked off!
